default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  host: localhost
  encoding: utf8mb4
  collation: utf8mb4_bin

development:
  <<: *default
  database: ApiTest_development

test: &test
  <<: *default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  host: localhost
  database: ApiTest_test
